logging:
  level:
    root: info
server:
  servlet:
    context-path: /
  port: 8099
spring:
  redis:
    database: 8
    host: lzlz.site
    port: 36379
    password: *
    timeout: PT1M
  datasource:
    url: jdbc:mysql://47.98.143.33/gobang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: *
    password: *
