logging:
  level:
    root: info
server:
  servlet:
    context-path: /
  port: 8099
spring:
  redis:
    database: 8
    host:
    port: 36379
    password:
    timeout: PT1M
  datasource:
    url:
    username:
    password: