name: Build & Deploy
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v2
      - name: maven build
        run: mvn -B package --file pom.xml
      - name: list build context
        uses: ll docker     
      - name: docker login
        uses: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.pkg.github.com
      - name: docker build
        uses: docker build -f docker/Dockerfile -t docker.pkg.github.com/yungyu16/gobang:latest
      - name: docker push
        uses: docker push docker.pkg.github.com/yungyu16/gobang:latest        
