name: Build & Deploy
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: maven build
        run: mvn -B package --file pom.xml
      - name: list build context
        run: ls -l docker
      - name: docker login
        env:
          USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO_PATH: ${{ 'docker.pkg.github.com/yungyu16/gobang/' }}
          IMG_NAME: ${{ 'gobang-dev' }}
        run: docker login -u $USER_NAME -p $PASSWORD docker.pkg.github.com
      - name: docker build
        run: docker build -t gobang-dev:latest docker
      - name: docker tag and push
        env:
          REPO_PATH: ${{ 'docker.pkg.github.com/yungyu16/gobang/' }}
          IMG_NAME: ${{ 'gobang-dev' }}
        run: TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          && docker tag gobang-dev:latest $REPO_PATH$IMG_NAME:$TIMESTAMP && docker push $REPO_PATH$IMG_NAME:$TIMESTAMP
          && docker tag gobang-dev:latest $REPO_PATH$IMG_NAME:latest && docker push $REPO_PATH$IMG_NAME:latest